export const SPREADSHEET_ID = process.env.GOOGLE_SHEET_ID || "";

export const SHEET_NAMES = {
  USERS: "Users",
  REFERRALS:               "Referrals",
  REFERRAL_REWARDS:        "Referral_Rewards",
  PASSWORD_RESET_REQUESTS: "Password_Reset_Requests",
  CAMPAIGNS:               "Campaigns",
  RETENTION_RECOMMENDATIONS: "Retention_Recommendations",
  TEAMS: "Teams",
  PLAYERS: "Players",
  GAMEWEEK: "Weekly_Gameweek",
  USER_LINEUPS: "User_Lineups",
  LINEUP_PLAYERS: "Lineup_Players",
  GAMES: "Games",
  PLAYER_STATS: "Player_Stats",
  FANTASY_SCORING: "Fantasy_Scoring",
  LEADERBOARD: "Leaderboard",
  SPONSORS: "Sponsors",
  SETTINGS:            "Settings",
  PLATFORM_SETTINGS:   "Platform_Settings",
  IMPORT_LOG:          "Import_Log",
  CALCULATION_BACKUP: "Calculation_Backup",
  ADMIN_ACTIONS_LOG: "Admin_Actions_Log",
  PRICE_HISTORY: "Price_History",
  LEAGUES: "Leagues",
  LEAGUE_MEMBERS: "League_Members",
  ACHIEVEMENTS: "Achievements",
  WATCHLISTS: "Watchlists",
  NOTIFICATIONS:            "Notifications",
  PUSH_SUBSCRIPTIONS:       "Push_Subscriptions",
  NOTIFICATION_PREFERENCES: "Notification_Preferences",
} as const;

export const SHEET_HEADERS: Record<string, string[]> = {
  [SHEET_NAMES.USERS]:     ["user_id","full_name","display_name","email","password_hash","phone","created_at","last_login","referral_code","referred_by","referral_date","password_temporary","temp_password_expires_at"],
  [SHEET_NAMES.REFERRALS]:        ["referrer_user_id","referred_user_id","referral_code","referral_date","status","qualified_at"],
  [SHEET_NAMES.REFERRAL_REWARDS]: ["reward_id","referral_id","referrer_user_id","referred_user_id","reward_type","reward_value","status","created_at","reviewed_at","paid_at","admin_id","payment_reference","admin_notes"],
  [SHEET_NAMES.PASSWORD_RESET_REQUESTS]: ["request_id","request_reference","user_id","phone","status","requested_at","actioned_at","actioned_by","admin_notes","expires_at"],
  [SHEET_NAMES.CAMPAIGNS]: ["campaign_id","title","subject","message","notification_type","audience_type","audience_filter","status","recipient_count","scheduled_at","sent_at","created_by","created_at","link","priority","delivery_duration_ms","channels","delivery_results","whatsapp_queue_status"],
  [SHEET_NAMES.RETENTION_RECOMMENDATIONS]: ["recommendation_id","recommendation_type","title","description","audience_type","audience_filter","recommended_subject","recommended_message","status","campaign_id","created_at","created_by","dismissed_at","completed_at"],
  [SHEET_NAMES.TEAMS]:   ["team_id","team_name","division","logo_url","status","created_at"],
  [SHEET_NAMES.PLAYERS]: ["player_id","full_name","team_id","position","fantasy_price","status","games_played","average_points","average_rebounds","average_assists","photo_url","import_alias","source","created_at"],
  [SHEET_NAMES.GAMEWEEK]: ["week_id","start_date","end_date","submission_deadline","is_locked","scores_calculated","prices_updated","created_at"],
  [SHEET_NAMES.USER_LINEUPS]: ["lineup_id","user_id","week_id","captain_player_id","total_score","submitted_at"],
  [SHEET_NAMES.LINEUP_PLAYERS]: ["lineup_id","player_id"],
  [SHEET_NAMES.GAMES]: ["game_id","home_team","away_team","game_date","status"],
  [SHEET_NAMES.PLAYER_STATS]: ["stat_id","game_id","player_id","points","rebounds","assists","steals","blocks","turnovers","minutes_played","fantasy_points"],
  [SHEET_NAMES.FANTASY_SCORING]: ["score_id","player_id","week_id","fantasy_points"],
  [SHEET_NAMES.LEADERBOARD]: ["leaderboard_id","week_id","user_id","score","rank"],
  [SHEET_NAMES.SPONSORS]: ["sponsor_id","name","logo_url","website_url","created_at"],
  [SHEET_NAMES.SETTINGS]:          ["setting_key","setting_value"],
  [SHEET_NAMES.PLATFORM_SETTINGS]: ["key","value","description"],
  [SHEET_NAMES.IMPORT_LOG]: ["import_id","file_name","game_id","imported_at","status"],
  [SHEET_NAMES.CALCULATION_BACKUP]: ["backup_id","week_id","backup_type","backup_data","created_at"],
  [SHEET_NAMES.ADMIN_ACTIONS_LOG]: ["action_id","admin_id","action_type","entity_type","entity_id","details","status","created_at"],
  [SHEET_NAMES.PRICE_HISTORY]: ["price_history_id","player_id","week_id","old_price","new_price","weekly_fantasy_points","created_at"],
  [SHEET_NAMES.LEAGUES]: ["league_id","league_name","description","invite_code","owner_user_id","max_members","visibility","status","created_at"],
  [SHEET_NAMES.LEAGUE_MEMBERS]: ["league_member_id","league_id","user_id","joined_at"],
  [SHEET_NAMES.ACHIEVEMENTS]: ["achievement_id","user_id","badge_key","badge_name","description","earned_at","week_id","metadata"],
  [SHEET_NAMES.WATCHLISTS]: ["watchlist_id","user_id","player_id","created_at"],
  [SHEET_NAMES.NOTIFICATIONS]: ["notification_id","user_id","type","title","message","link","status","priority","metadata","created_at","expires_at"],
  [SHEET_NAMES.PUSH_SUBSCRIPTIONS]: ["subscription_id","user_id","endpoint","p256dh","auth","device_label","user_agent","created_at","last_used_at","status"],
  [SHEET_NAMES.NOTIFICATION_PREFERENCES]: ["pref_id","user_id","push_enabled","categories","quiet_hours_start","quiet_hours_end","updated_at"],
};
